[versions]
minSdk = "28"
targetSdk = "35"
compileSdk = "35"


agp = "8.4.0"
#kotlin = "1.9.23"
kotlin = "2.1.10"
ksp = "2.1.10-1.0.31"
android-maven-plugin = "2.1"
androidTools = "31.5.0"

multidex = "2.0.0"
activityx-fragment-ktx = "1.5.2"
core-ktx = "1.9.0"
appcompat = "1.2.0"
constraintlayout = "2.1.0"
activityx-ktx = "1.9.1"
lifecycle-runtime-ktx = "2.8.7"
glide = "4.16.0"
glide-transformation = "4.3.0"
junit = "4.13.2"
ext-junit = "1.1.4"
espresso-core = "3.5.0"
androidx-compose-bom = "2024.10.01"
androidx-compose-ui = "1.5.0"
androidx-compose-runtime = "1.5.0"
androidx-hilt-navigation-compose = "1.1.0"
androidx-compose-activity = "1.9.2"
androidx-compose-lifecycle-viewmodel = "2.8.5"
androidx-comopse-constraintlayout = "1.0.1"
compose-coil = "2.5.0"

media3 = "1.7.1"

google-accompanist-pager = "0.28.0"
google-accompanist-pager-indicators = "0.28.0"
google-accompanist-drawablepainter = "0.32.0"
threetenapb = "1.3.0"
jetbrainsKotlinJvm = "1.9.0"
timber = "5.0.1"

retrofit = "2.9.0"
hazeVerion = "1.3.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }

# Custom Convention Plugin
codehong-lib-android-application = { id = "codehong.lib.android.application", version = "unspecified" }
codehong-lib-android-application-compose = { id = "codehong.lib.android.application.compose", version = "unspecified" }
codehong-lib-android-library = { id = "codehong.lib.android.library", version = "unspecified" }
codehong-lib-android-library-compose = { id = "codehong.lib.android.library.compose", version = "unspecified" }
codehong-lib-android-library-publishing = { id = "codehong.lib.library.publishing", version = "unspecified" }



[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
haze = { group = "dev.chrisbanes.haze", name = "haze", version.ref = "hazeVerion" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }


androidx-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment", version.ref = "activityx-fragment-ktx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityx-ktx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activityx-ktx" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version = "1.3.1" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version = "1.1.0" }

material = { group = "com.google.android.material", name = "material", version = "1.12.0" }

glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
#glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
glide-transformation = { group = "jp.wasabeef", name = "glide-transformations", version.ref = "glide-transformation" }
glide-ksp = { group = "com.github.bumptech.glide", name = "ksp", version.ref = "glide" }

# test
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }


# compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidx-compose-ui" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "androidx-compose-runtime" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidx-hilt-navigation-compose" }
androidx-compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-compose-activity" }
androidx-compose-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-compose-lifecycle-viewmodel" }
androidx-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
androidx-compose-rxjava2 = { group = "androidx.compose.runtime", name = "runtime-rxjava2" }
androidx-compose-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "androidx-comopse-constraintlayout" }
androidx-compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive" }
andoridx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
coil = { group = "io.coil-kt", name = "coil", version.ref = "compose-coil" }
#coil-transformations = { group = "io.coil-kt", name = "coil-transformations", version.ref = "compose-coil" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "compose-coil" }

# exoplayer
androidx-media = { group = "androidx.media", name = "media", version = "1.5.0" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
androidx-media3-exoplayer-hls = { group = "androidx.media3", name = "media3-exoplayer-hls", version.ref = "media3" }
androidx-media3-common-ktx = { group = "androidx.media3", name = "media3-common-ktx", version.ref = "media3" }
androidx-media3-datasource = { group = "androidx.media3", name = "media3-datasource", version.ref = "media3" }

# google
google-accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "google-accompanist-pager" }
google-accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "google-accompanist-pager-indicators" }
google-accompanist-drawablepainter = { group = "com.google.accompanist", name = "accompanist-drawablepainter", version.ref = "google-accompanist-drawablepainter" }
google-accompanist-flowlayout = { group = "com.google.accompanist", name = "accompanist-flowlayout", version = "0.36.0" }

# etc
threetenapb = { group = "com.jakewharton.threetenabp", name = "threetenabp", version.ref = "threetenapb" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

android-maven-gradle-plugin = { module = "com.github.dcendents:android-maven-gradle-plugin", version.ref = "android-maven-plugin" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version = "4.11.0" }



[bundles]
